"""SOAP note read / edit / sign / export endpoints."""
from __future__ import annotations

import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy.orm import Session

from ..db import get_db
from ..models.note import Note, NoteStatus
from ..models.visit import Visit
from ..schemas.note import NoteOut, NoteUpdate, SignNoteIn

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/visits/{visit_id}/note", tags=["notes"])


def _get_note_or_404(visit_id: str, db: Session) -> Note:
    visit = db.get(Visit, visit_id)
    if visit is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Visit {visit_id} not found")
    if visit.note is None:
        raise HTTPException(
            status.HTTP_409_CONFLICT,
            "Note not yet generated. Wait for visit.status == 'ready'.",
        )
    return visit.note


@router.get("", response_model=NoteOut)
def get_note(visit_id: str, db: Session = Depends(get_db)) -> Note:
    return _get_note_or_404(visit_id, db)


@router.patch("", response_model=NoteOut)
def update_note(visit_id: str, payload: NoteUpdate, db: Session = Depends(get_db)) -> Note:
    note = _get_note_or_404(visit_id, db)
    if note.status == NoteStatus.SIGNED:
        raise HTTPException(status.HTTP_409_CONFLICT, "Cannot edit a signed note")

    data = payload.model_dump(exclude_unset=True)
    for k, v in data.items():
        setattr(note, k, v)
    if data:
        note.status = NoteStatus.EDITED
    db.add(note)
    db.commit()
    db.refresh(note)
    return note


@router.post("/sign", response_model=NoteOut)
def sign_note(visit_id: str, payload: SignNoteIn, db: Session = Depends(get_db)) -> Note:
    note = _get_note_or_404(visit_id, db)
    if note.status == NoteStatus.SIGNED:
        raise HTTPException(status.HTTP_409_CONFLICT, "Note already signed")

    note.signed_by = payload.signed_by
    note.signed_at = datetime.now(timezone.utc)
    note.status = NoteStatus.SIGNED
    db.add(note)
    db.commit()
    db.refresh(note)
    logger.info("note signed visit=%s by=%s", visit_id, payload.signed_by)
    return note


@router.get("/export.txt", response_class=Response)
def export_note_text(visit_id: str, db: Session = Depends(get_db)) -> Response:
    """Plain-text export — stand-in for the future FHIR/HL7 EHR push."""
    note = _get_note_or_404(visit_id, db)
    visit = note.visit

    lines: list[str] = []
    lines.append("=" * 64)
    lines.append("MEDICS4ALL — CLINICAL NOTE")
    lines.append("=" * 64)
    lines.append(f"Visit ID:       {visit.id}")
    lines.append(f"Clinician:      {visit.clinician_name}")
    lines.append(f"Patient:        {visit.patient_label}")
    lines.append(f"Visit time:     {visit.created_at.isoformat()}")
    lines.append(f"Status:         {note.status.value}")
    if note.signed_by:
        lines.append(f"Signed by:      {note.signed_by} at {note.signed_at.isoformat() if note.signed_at else ''}")
    lines.append("")
    lines.append(f"Chief Complaint: {note.chief_complaint or '-'}")
    if note.icd10_codes:
        lines.append(f"ICD-10:          {note.icd10_codes}")
    lines.append("")
    lines.append("--- SUBJECTIVE ---")
    lines.append(note.subjective or "-")
    lines.append("")
    lines.append("--- OBJECTIVE ---")
    lines.append(note.objective or "-")
    lines.append("")
    lines.append("--- ASSESSMENT ---")
    lines.append(note.assessment or "-")
    lines.append("")
    lines.append("--- PLAN ---")
    lines.append(note.plan or "-")
    if note.medications:
        lines.append("")
        lines.append("--- MEDICATIONS ---")
        lines.append(note.medications)
    lines.append("")
    lines.append("=" * 64)
    lines.append("Generated by Medics4ALL Core Scribe — clinician review required.")

    body = "\n".join(lines)

    if note.status == NoteStatus.SIGNED:
        note.status = NoteStatus.EXPORTED
        db.add(note)
        db.commit()

    return Response(
        content=body,
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="visit-{visit_id}.txt"'},
    )
